/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Ar G H-o
 */
public class ForLenght extends javax.swing.JFrame {

    /**
     * Creates new form ForLenght
     */
    public ForLenght() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JComboBox<>();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JComboBox<>();
        c = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1119, 550));
        setMinimumSize(new java.awt.Dimension(1119, 550));
        setPreferredSize(new java.awt.Dimension(1119, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 380, 48, 36);

        b2.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        b2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeter", "Inch", "Feet", "Meter" }));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(640, 270, 301, 75);

        t2.setEditable(false);
        getContentPane().add(t2);
        t2.setBounds(640, 190, 300, 50);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(90, 190, 290, 50);

        b1.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        b1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeter", "Inch", "Feet", "Meter" }));
        b1.setToolTipText("");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(80, 270, 301, 75);

        c.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        c.setText("Convert");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(440, 250, 140, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\Project - Measurement Converter\\IMG-2903.JPG")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1119, 550));
        jLabel2.setMinimumSize(new java.awt.Dimension(1119, 550));
        jLabel2.setPreferredSize(new java.awt.Dimension(1119, 550));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-70, 0, 1220, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        P00001__Choice_1 main = new P00001__Choice_1();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        main.setTitle("Converter");
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

    }//GEN-LAST:event_b2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

    }//GEN-LAST:event_b1ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        String bs1 = (String) b1.getSelectedItem();
        String s1 = t1.getText();
        String bs2 = (String) b2.getSelectedItem();
        double v = Double.valueOf(s1);
        if (bs1.equals("Centimeter")) {
            if (bs2.equals("Centimeter")) {
                t2.setText(s1);
            } else if (bs2.equals("Inch")) {
                v = v * 0.394;
                t2.setText(Double.toString(v));
            } else if (bs2.equals("Feet")) {
                v = v * 0.0328;
                t2.setText(Double.toString(v));
            } else if (bs2.equals("Meter")) {
                v = v * 0.01;
                t2.setText(Double.toString(v));
            }
        } else if (bs1.equals("Meter")) {
            if (bs2.equals("Meter")) {
                t2.setText(s1);
            } else if (bs2.equals("Centimeter")) {
                v = v * 100;
                t2.setText(Double.toString(v));
            } else if (bs2.equals("Inch")) {
                v = v * 39.37;
                t2.setText(Double.toString(v));
            } else if (bs2.equals("Feet")) {
                v = v * 3.28;
                t2.setText(Double.toString(v));
            }
    }//GEN-LAST:event_cActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> b1;
    private javax.swing.JComboBox<String> b2;
    private javax.swing.JButton c;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
